### ISSUE TITLE
Build humble images on arm64

### ISSUE THREAD

**Issue by tiesus** [ika-rwth-aachen/docker-ros-ml-images#6]
Currently the ros2 ml images do not support humble for arm64. Since jetpack 6 supports ubuntu 22.04 are their any plans to add this images to the pipeline?

**Comment by lreiher** [comment]
We are currently evaluating different options for releasing arm64 images with ROS 2 Humble and will come back to this issue soon!

**Comment by tiesus** [comment]
Thanks for your effort. That really helps us!

**Comment by lreiher** [comment]
May I ask what kinds of applications you are using this for and what of the ML frameworks you are using? :)

**Comment by tiesus** [comment]
Of course. We develop software for use cases in agriculture. We mainly use PyTorch for segmentation tasks.
